### ISSUE TITLE
Подключение UI

### ISSUE THREAD

**Issue by mayamika** [mayamika/cellay#1]
Пока не особо понятно как будет происходить сам процесс игры, но вот моя идея.

1. Сообщаем о желании поиграть через `POST /matches`, получаем какой-то токен
2. С этим токеном получаем какие-то credentials через `GET /matches/{id}`
3. Подключаемся к центрифуге

Видимо, для начала будет один канал, по которому будут приходить стейты следующего вида:
```
type State struct {
	Table map[string][][]int // maps layer name to [col][row]
	Event *Event             `json:",omitempty"`
}
```
В каждом стейте может быть эвент следующего вида:
```
//go:generate ${TOOLS_PATH}/enumer -type EventType -trimprefix EventType -json -text -transform=snake
type EventType int8

const (
	EventTypeUnknown EventType = iota
	EventTypeWin
	EventTypeDraw
	EventTypeNotification
)

type Event struct {
	Type    EventType
	Player  int    `json:",omitempty"`
	Message string `json:",omitempty"`
}
```
На сервер можно посылать какие-то действия, пока это клик или перемещение:
```
type Coords struct {
	X int
	Y int
}

type Click struct {
	Coords
	Player int
}

type Move struct {
	From   Coords
	To     Coords
	Player int
}
```
Поля Player будут заполнены на бэкенде

**Comment by Darkclainer** [comment]
Уже думал об этом, есть у меня следующие комментарии. Попробую немного систематизировать ещё написанное тобой.

### Create game

Нужно API для создания новой сессии игры. То есть когда игрок выбрал игру из списка, он при клике на неё автоматически создаёт новую сессию, id которой получает и видит на экране (пока никто не присоединился). 

`GET /api/v1/match/new/{game_id}`

На что он получается response:

```json
{
  "session": "session hex number",
  "key": "session key"
}
```

`session` --- это какая-то последовательность символов, чтобы второй игрок мог подключиться к игре (и бек мог понимать о какой игре идёт речь в разных крайних случаях)

`key` --- ключ до сессии. Он нужен, чтобы при перезагрузке коннекта, игрок мог восстановить доступ, или игроки не менялись местами. Короче говоря, чтобы ты мог правильно понять где игрок 1, а где игрок 2. Идеально это сохрянить в куки (на ui я это не могу сделать). В целом можно это сохранить в storage на ui, он не секьюрный, но какая разница. Можно ещё заставить игрока вводить его руками, но эт сосвсем говно.

### Get session info

Метод для получения информации об игре по сессии.
Идея такая: ui нужно подключиться к игре, следовательно ему нужно сделать несколько действий

1. Скачать ассеты игры
2. Получить session key (если он новый игрок)
3. Открыть канал в центрифуге

Как бы много действий для одного api, которое ещё не может быть сделано через protobuf, поэтому нужен отдельный метод.
Он получает id игры (для ассетов) и session key, если нужен.

`GET /api/v1/match/info/{session}?new=true`

Ответ:

```json
{
  "game_id": 123,
  "key": "session key"
}
```

После этого метода ui может начать качать ассеты, переходить на нужную страницу + менеджмент ключа игры номрально идёт.

### Connect to game

Метод для подключения к каналу.

После того как ui подготовился к игре, ui может создать в цетрифуге новый канал (или сделать запрос на определённый) с помощью session key и уже с помощью него общаться
